const fs = require('fs');
let c = fs.readFileSync('src/controllers/MDReportController.ts', 'utf8');

c = c.replace(
    /sale: \{ marketer: \{ branchId: branchId as string \} \} \/\/ Only payments generated by this branch's marketers/,
    `OR: [
                    { sale: { marketer: { branchId: branchId as string } } },
                    { sale: { plot: { estate: { managingBranchId: branchId as string } } } }
                ]`
);

fs.writeFileSync('src/controllers/MDReportController.ts', c);
